---

- name: Search item_id
  ansible.builtin.include_tasks:
    file: api/search/item_id.yaml
  when: not item.body.id is defined


- name: Search entities_id
  ansible.builtin.include_tasks:
    file: api/search/entities_id.yaml
  when: item.entities_id is defined


- name: Search groups_id
  ansible.builtin.include_tasks:
    file: api/search/groups_id.yaml
  when: item.groups_id is defined


- name: Search itilcategories_id
  ansible.builtin.include_tasks:
    file: api/search/itilcategories_id.yaml
  when: item.itilcategories_id is defined


- name: Search tickettemplates_id_demand
  ansible.builtin.include_tasks:
    file: api/search/itickettemplates_id_demand.yaml
  when: item.tickettemplates_id_demand is defined


- name: Search tickettemplates_id
  ansible.builtin.include_tasks:
    file: api/search/tickettemplates_id.yaml
  when: item.tickettemplates_id is defined


- name: Search users_id
  ansible.builtin.include_tasks:
    file: api/search/users_id.yaml
  when: item.users_id is defined
